baseurl = "https://silvia-peracchi-econ.netlify.app/" # Hostname (and path) to the root.
title = "Silvia Peracchi" # Site title.
theme = "hugo-coder1" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "silviaperacchi" # Enable or disable Disqus.

#added to read html code for images
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params] # theme parameters
    author = "Silvia Peracchi" # Author's name.
    info = "Economist" # Author's job title or info.
    description = "Silvia Peracchi's personal website" # Site description.
    keywords = "economics" # Site keywords.
    avatarurl = "images/silvia_emoji-computer.jpg" # Contain the path of the optionnal avatar in the static folder.
    colorScheme = "light"
    hideColorSchemeToggle = false

    footercontent = "" # Add footer content
    fixedbarContent = "Wanna write me an e-mail? " # Add fixedbar content
    fixedbarContentAfter = "silvia.peracchi.sp@gmail.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = ["css/custom.css"]
    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

[params.googleTagManager]
    id = "gid"

    
#Analytics
 [params.goatCounter]
 code = "peracchisilviapersonalwebsite1234567"
# You will access your account at https://peracchisilviapersonalwebsite1234567.goatcounter.com


# Social links
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Sil-Per"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/silvia-peracchi-3a9655ba/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/SilviaPeracchi"

# Menu links
[[menu.main]]
    name = "Research"
    weight = 1
    url  = "research"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name = "Credits"
    weight = 3
    url = "credits"
[[menu.main]]
name = "Blog"
weight = 2
url = "posts"
